language: node_js
install: true
script: true
after_success:
 - scp -i "se234.pem" -r html/* ubuntu@54.255.174.42:/var/www/html/

before_install:
- openssl aes-256-cbc -k "$super_secret_password" -in se234.pem.enc -out
se234.pem -d